pipeline {
    agent any

    environment {
        AWS_REGION = 'af-south-1'
        AWS_ACCOUNT_ID = '522237065210'
        ECR_REPO = 'my-app-latest-repo'
        DOCKER_IMAGE_TAG = "latest-${env.BUILD_NUMBER}"
        ECS_CLUSTER = 'devops-cluster'
        ECS_SERVICE = 'devops-service'
        EC2_INSTANCE_HOST = '13.247.62.21'  // Updated to your app EC2 public IP
        SSH_KEY_PATH = '/home/ubuntu/keys/devops3-key.pem'
    }

    options {
        timestamps()
        timeout(time: 45, unit: 'MINUTES') 
        retry(2) 
    }

    stages {

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker image..."
                    sh "docker build -t ${ECR_REPO}:${DOCKER_IMAGE_TAG} ./app"
                }
            }
        }

        stage('Login to ECR') {
            steps {
                script {
                    echo "Logging into AWS ECR..."
                    sh """
                        aws ecr get-login-password --region $AWS_REGION | \
                        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                    """
                }
            }
        }

        stage('Push Docker Image to ECR') {
            steps {
                script {
                    echo "Tagging Docker image..."
                    sh "docker tag ${ECR_REPO}:${DOCKER_IMAGE_TAG} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${ECR_REPO}:${DOCKER_IMAGE_TAG}"
                    
                    echo "Pushing Docker image..."
                    sh "docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${ECR_REPO}:${DOCKER_IMAGE_TAG}"
                }
            }
        }

        stage('Deploy to ECS Fargate') {
            steps {
                script {
                    echo "Updating ECS service..."
                    sh """
                        aws ecs update-service \
                            --cluster ${ECS_CLUSTER} \
                            --service ${ECS_SERVICE} \
                            --force-new-deployment \
                            --region ${AWS_REGION}
                    """
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                script {
                    echo "Deploying Docker container to EC2..."
                    sh """
                        ssh -o StrictHostKeyChecking=no -i ${SSH_KEY_PATH} ubuntu@${EC2_INSTANCE_HOST} \\
                        'echo Starting deployment... && \\
                         docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${ECR_REPO}:${DOCKER_IMAGE_TAG} && \